POST http://localhost:3001/users/login HTTP/1.1
content-type: application/json

{
    "email": "yosi@mail.com",
    "password": "123456"
}

####

GET Http://localhost:3001/ HTTP/1.1

####

GET Http://localhost:3001/upload/folders HTTP/1.1

####